<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>sincronizador</AssemblyName>
    <AssemblyTitle>ReprediSL Sincronizador de Pedidos</AssemblyTitle>
    <Product>ReprediSL V4</Product>
    <Version>4.9.2</Version>
    <AssemblyVersion>4.9.2.0</AssemblyVersion>
    <FileVersion>4.9.2.0</FileVersion>
  </PropertyGroup>

</Project>
