db-uri = "postgres://authenticator@localhost:5433/repredisl_api"
db-schemas = "api"
db-anon-role = "web_anon"

server-host = "127.0.0.1"
server-port = 3000

server-cors-allowed-origins = "https://pedidos.repredisl.com"
